apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pos
  labels:
    app: {{ include "hcen-pos.name" . }}
    chart: {{ include "hcen-pos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sys: {{ .Values.global.sysName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hcen-pos.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "hcen-pos.fullname" . }}
      labels:
        app: {{ include "hcen-pos.name" . }}
        chart: {{ include "hcen-pos.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        sys: {{ .Values.global.sysName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: DB2_PASSWORD
            value: {{ .Values.global.db2Password }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
