apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pos
  labels:
    app: {{ include "hcen-pos.name" . }}
    chart: {{ include "hcen-pos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sys: {{ .Values.global.sysName }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image }}"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: http
      readinessProbe:
        httpGet:
          path: /
          port: http
