apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pos
  labels:
    app: {{ include "hcen-pos.name" . }}
    chart: {{ include "hcen-pos.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sys: {{ .Values.global.sysName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "hcen-pos.name" . }}
    release: {{ .Release.Name }}
