apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  labels:
    app: {{ include "nats-stream.name" . }}
    chart: {{ include "nats-stream.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sys: {{ .Values.global.sysName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4222
      protocol: TCP
      name: nats
  selector:
    app: {{ include "nats-stream.name" . }}
    release: {{ .Release.Name }}
