# Default values for db2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  sysName: db2

  # Name of host that holds local persisten volumes.
  statefulHostName: minikube

image: ibmcom/db2:11.5.0.0a

service:
  type: NodePort
  port: 50000

db2Password: Please-change-this-default-password.
dbName: testdb

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
