apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rec
  labels:
    app: {{ include "hcen-rec.name" . }}
    chart: {{ include "hcen-rec.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sys: {{ .Values.global.sysName }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ include "hcen-rec.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "hcen-rec.fullname" . }}
      labels:
        app: {{ include "hcen-rec.name" . }}
        chart: {{ include "hcen-rec.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        sys: {{ .Values.global.sysName }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: DB2_PASSWORD
            value: {{ .Values.global.db2Password }}
          - name: NATS_URL
            value: "nats://{{ .Release.Name }}-nats:4222"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
